services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: './Dockerfile.dev'
    volumes:
      - './:/app/'
    networks:
      - main
  backend:
    env_file: development.env
    build: 
      context: ./backend
      dockerfile: './Dockerfile.dev'
    volumes:
      - './:/app/'
    networks:
      - main
  db:
    image: postgres
    env_file: development.env
    networks:
      - main
    ports:
      - 5432:5432
  pgadmin:
    env_file: development.env
    image: dpage/pgadmin4
    networks:
      - main
    ports:
      - 3001:80
  nginx:
    image: nginx:alpine
    networks:
      - main
    ports:
      - 3000:80
    volumes:
      - "./proxy/nginx.dev.conf:/etc/nginx/nginx.conf"
  watcher:
    build: ./openapi
    volumes:
      - "./:/app"

networks:
  main:
