services:
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - main
  backend:
    env_file: production.env
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - main
  nginx:
    image: nginx:alpine
    networks:
      - main
    ports:
      - 3000:80
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"

networks:
  main:
