services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
  backend:
    env_file: development.env
    build: ./backend
    volumes:
      - ./backend:/backend
    networks:
      - main
    ports:
      - 3001:3000
  db:
    image: postgres
    env_file: development.env
    networks:
      - main
  pgadmin:
    env_file: development.env
    image: dpage/pgadmin4
    networks:
      - main
    ports:
      - 3002:80

networks:
  main: