services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    networks:
      - main
  backend:
    env_file: development.env
    build: ./backend
    volumes:
      - ./backend:/backend
    networks:
      - main
  db:
    image: postgres
    env_file: development.env
    networks:
      - main
  pgadmin:
    env_file: development.env
    image: dpage/pgadmin4
    networks:
      - main
    ports:
      - 3001:80
  nginx:
    image: nginx:alpine
    networks:
      - main
    ports:
      - 3000:80
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"

networks:
  main: